name: Android Action Generated APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  upload_dev_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Create keystore.properties file
        run: echo "${{ secrets.JUST_VERONICA }}" > keystore.properties

      - name: JUST CHILL
        run: |
          mkdir -p key
          echo "${{ secrets.JUST_CHILL }}" | base64 --decode > key/just_chill_key.p12

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Dev Debug (assembleDevDebug)
        run: ./gradlew assembleDebug

      - name: Get Dev Debug APK path
        id: devDebugPath
        run: echo "devDebug=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_OUTPUT

      - name: upload DEV DEBUG (APP DISTRIBUTION)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_DEV_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: EMM
          file: ${{ steps.devDebugPath.outputs.devDebug }}
